services:
  - type: web
    name: magicmuse
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: CI
        value: true
